openapi: 3.0.3
info:
  title: Swagger Demo API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/hello:
    get:
      summary: Say hello
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello from Swagger API

